# Generated by Django 2.0.13 on 2020-03-31 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0002_auto_20200330_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sct',
            name='sct_type',
        ),
        migrations.AddField(
            model_name='sct',
            name='sct_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrytool.SCTType'),
        ),
        migrations.AddField(
            model_name='sct',
            name='sct_type_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
