# Generated by Django 2.0.13 on 2020-09-30 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0003_auto_20200930_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='followup_date',
        ),
        migrations.AddField(
            model_name='followup',
            name='follow_up_date',
            field=models.DateField(default=datetime.date(1999, 12, 12), verbose_name='Visit date'),
            preserve_default=False,
        ),
    ]
