# Generated by Django 2.0.13 on 2020-03-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0004_auto_20200331_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='mgus_history_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='death_cause',
            field=models.CharField(choices=[('D', 'Disease'), ('C', 'Complications of Disease'), ('O', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='del_17p',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='mgus_history',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='smm_history',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='t4_14',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='t4_16',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], max_length=10),
        ),
    ]
