# Generated by Django 2.0.13 on 2020-09-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0038_auto_20191206_1449'),
        ('entrytool', '0004_auto_20200930_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='episode',
        ),
        migrations.AddField(
            model_name='followup',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opal.Patient'),
            preserve_default=False,
        ),
    ]
