# Generated by Django 2.0.13 on 2020-03-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0005_auto_20200331_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='diag_date',
            field=models.DateField(null=True),
        ),
    ]
