# Generated by Django 2.0.13 on 2020-10-01 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0006_auto_20201001_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='regimen',
            name='stop_reason',
        ),
        migrations.AddField(
            model_name='regimen',
            name='stop_reason_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='stopreason',
            unique_together={('code', 'system')},
        ),
        migrations.AddField(
            model_name='regimen',
            name='stop_reason_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrytool.StopReason'),
        ),
    ]
