# Generated by Django 2.0.13 on 2020-03-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0006_auto_20200331_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='death_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='smm_history_date',
            field=models.DateField(null=True),
        ),
    ]
