# Generated by Django 2.0.13 on 2020-10-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0007_auto_20201001_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimen',
            name='category',
            field=models.CharField(choices=[('Induction', 'Induction'), ('Maintenance', 'Maintenance'), ('Conditioning', 'Conditioning')], default='', max_length=40, verbose_name='Regimen Type'),
            preserve_default=False,
        ),
    ]
