# Generated by Django 2.0.13 on 2020-10-02 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0008_regimen_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='hospital',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='hospital_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrytool.Hospital'),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='hospital_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
