# Generated by Django 2.0.13 on 2020-04-01 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0038_auto_20191206_1449'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrytool', '0008_auto_20200331_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('severity', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V')], max_length=4, verbose_name='Severity')),
                ('ae_date', models.DateField(verbose_name='Date of AE')),
                ('adverse_event_ft', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AEList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entrytool_followup_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entrytool_followup_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('response_date', models.DateField()),
                ('response', models.CharField(choices=[('MR', 'Minimal response'), ('PR', 'Partial response'), ('VGPR', 'Very good partial response'), ('CR', 'Complete response'), ('SCR', 'Stringent complete response'), ('NCR', 'Near complete response'), ('ICR', 'Immunophenotypic complete response'), ('SD', 'Stable disease'), ('PD', 'Progressive disease'), ('RU', 'Response unknown')], max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entrytool_response_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entrytool_response_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='SCTType',
        ),
        migrations.RemoveField(
            model_name='sct',
            name='sct_type_fk',
        ),
        migrations.RemoveField(
            model_name='sct',
            name='sct_type_ft',
        ),
        migrations.AddField(
            model_name='sct',
            name='sct_type',
            field=models.CharField(choices=[('1', 'Allogenic'), ('2', 'Autologous'), ('3', 'Unknown')], max_length=12, null=True, verbose_name='Type of SCT'),
        ),
        migrations.AlterField(
            model_name='regimen',
            name='stop_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Reason for Regimen Stop'),
        ),
        migrations.AlterField(
            model_name='sct',
            name='sct_date',
            field=models.DateField(verbose_name='Date of SCT'),
        ),
        migrations.AlterUniqueTogether(
            name='aelist',
            unique_together={('code', 'system')},
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='adverse_event_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrytool.AEList'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entrytool_adverseevent_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entrytool_adverseevent_subrecords', to=settings.AUTH_USER_MODEL),
        ),
    ]
