# Generated by Django 2.0.13 on 2020-10-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0009_auto_20201002_1117'),
        ('entrytool', '0009_auto_20201002_1039'),
    ]

    operations = [
    ]
