# Generated by Django 2.0.13 on 2020-04-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0010_auto_20200401_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='death_cause',
            field=models.CharField(blank=True, choices=[('D', 'Disease'), ('C', 'Complications of Disease'), ('O', 'Other')], max_length=100, null=True, verbose_name='Cause of Death'),
        ),
    ]
