# Generated by Django 2.0.13 on 2020-10-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0010_merge_20201002_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='mgus_history_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of MGUS Diagnosis'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='smm_history_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of SMM diagnosis'),
        ),
    ]
