# Generated by Django 2.0.13 on 2020-04-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0012_auto_20200402_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regimen',
            name='lot_fk',
        ),
        migrations.RemoveField(
            model_name='regimen',
            name='lot_ft',
        ),
    ]
