# Generated by Django 2.0.13 on 2020-10-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0012_auto_20201005_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='external_identifier',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
