# Generated by Django 2.0.13 on 2020-10-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0012_auto_20201005_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='Hb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='LDH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='MCV',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='albumin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='beta2m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='creatinin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
