# Generated by Django 2.0.13 on 2020-04-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0013_auto_20200402_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimen',
            name='lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entrytool.TreatmentLine', verbose_name='Line of Treatment'),
            preserve_default=False,
        ),
    ]
