# Generated by Django 2.0.13 on 2020-10-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0013_auto_20201006_2003'),
        ('entrytool', '0013_demographics_external_identifier'),
    ]

    operations = [
    ]
