# Generated by Django 2.0.13 on 2020-04-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0014_regimen_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regimen',
            name='lot',
        ),
        migrations.AddField(
            model_name='regimen',
            name='lot_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrytool.TreatmentLine'),
        ),
        migrations.AddField(
            model_name='regimen',
            name='lot_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
