# Generated by Django 2.0.13 on 2020-10-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0014_merge_20201007_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='condition_fk',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='location',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='location',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
