# Generated by Django 2.0.13 on 2020-10-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0015_auto_20201007_1227'),
        ('entrytool', '0013_patientdetails_lost_to_follow_up_date'),
    ]

    operations = [
    ]
