# Generated by Django 2.0.13 on 2020-04-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0017_auto_20200402_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regimen',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
    ]
