# Generated by Django 2.0.13 on 2020-10-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0017_auto_20201007_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aelist',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='aelist',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='aelist',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='aelist',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='regimenlist',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='regimenlist',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='regimenlist',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='regimenlist',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='stopreason',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='stopreason',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stopreason',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='stopreason',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Version'),
        ),
    ]
