# Generated by Django 2.0.13 on 2020-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0018_auto_20201007_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='external_identifier',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='External Identifier'),
        ),
    ]
