# Generated by Django 2.0.13 on 2020-04-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0018_auto_20200402_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverseevent',
            name='lot',
            field=models.IntegerField(default=0, verbose_name='Line of Treatment'),
            preserve_default=False,
        ),
    ]
