# Generated by Django 2.0.13 on 2020-10-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0016_merge_20201007_1605'),
        ('entrytool', '0019_auto_20201007_1557'),
    ]

    operations = [
    ]
