# Generated by Django 2.0.13 on 2020-04-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0019_adverseevent_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='FollowUp',
        ),
    ]
