# Generated by Django 2.0.13 on 2020-10-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0020_merge_20201007_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='lost_to_follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lost to Follow-up'),
        ),
    ]
