# Generated by Django 2.0.13 on 2020-04-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0022_auto_20200403_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographics',
            name='hospital',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='hospital',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='status',
            field=models.CharField(choices=[('T', 'Under Treatment'), ('D', 'Dead'), ('LFU', 'Lost to Follow-up')], default='', max_length=100, verbose_name='Patient Status'),
            preserve_default=False,
        ),
    ]
