# Generated by Django 2.0.13 on 2020-10-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0022_auto_20201012_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='r_iss_stage',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='iss_stage',
            field=models.CharField(choices=[('Stage I', 'Stage I'), ('Stage II', 'Stage II'), ('Stage III', 'Stage III')], default='Unknown', max_length=10, verbose_name='ISS Stage'),
            preserve_default=False,
        ),
    ]
