# Generated by Django 2.0.13 on 2020-04-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0023_auto_20200403_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Death'),
        ),
    ]
