# Generated by Django 2.0.13 on 2020-10-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0023_auto_20201016_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='del_13',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default='Unknown', max_length=10, verbose_name='del13'),
            preserve_default=False,
        ),
    ]
