# Generated by Django 2.0.13 on 2020-04-03 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0024_auto_20200403_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimen',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entrytool.TreatmentLine'),
        ),
    ]
