# Generated by Django 2.0.13 on 2020-10-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0024_patientdetails_del_13'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='ds_stage',
            field=models.CharField(choices=[('Stage I', 'Stage I'), ('Stage II', 'Stage II'), ('Stage III', 'Stage III'), ('Unknown', 'Unknown')], default='Unknown', max_length=10, verbose_name='DS Stage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='iss_stage',
            field=models.CharField(choices=[('Stage I', 'Stage I'), ('Stage II', 'Stage II'), ('Stage III', 'Stage III'), ('Unknown', 'Unknown')], max_length=10, verbose_name='ISS Stage'),
        ),
    ]
