# Generated by Django 2.0.13 on 2020-04-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0025_regimen_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='followup_date',
            field=models.DateField(default='1999-12-12', verbose_name='Visit date'),
        ),
    ]
