# Generated by Django 2.0.13 on 2020-04-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0026_followup_followup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regimen',
            name='line',
        ),
    ]
