# Generated by Django 2.0.13 on 2020-10-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0027_auto_20201019_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='mprotein_24h',
            field=models.FloatField(blank=True, null=True, verbose_name='Mprotein in 24 hour urine'),
        ),
    ]
