# Generated by Django 2.0.13 on 2021-01-26 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0039_auto_20201007_1245'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrytool', '0028_followup_mprotein_24h'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodCountFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('followup_date', models.DateField(verbose_name='Visit date')),
                ('erythrocytes', models.FloatField(blank=True, null=True, verbose_name='erythrocytes')),
                ('hemoglobin', models.FloatField(blank=True, null=True, verbose_name='hemoglobin')),
                ('hematocrit', models.FloatField(blank=True, null=True, verbose_name='hematocrit')),
                ('mcv', models.FloatField(blank=True, null=True, verbose_name='mcv')),
                ('mch', models.FloatField(blank=True, null=True, verbose_name='mch')),
                ('mchc', models.FloatField(blank=True, null=True, verbose_name='mchc')),
                ('reticulocytes', models.FloatField(blank=True, null=True, verbose_name='reticulocytes')),
                ('leucocytes', models.FloatField(blank=True, null=True, verbose_name='leucocytes')),
                ('myeloblasts', models.FloatField(blank=True, null=True, verbose_name='myeloblasts')),
                ('promyelocytes', models.FloatField(blank=True, null=True, verbose_name='promyelocytes')),
                ('myelocytes', models.FloatField(blank=True, null=True, verbose_name='myelocytes')),
                ('eosinophils', models.FloatField(blank=True, null=True, verbose_name='eosinophils')),
                ('basophils', models.FloatField(blank=True, null=True, verbose_name='basophils')),
                ('lymphocytes', models.FloatField(blank=True, null=True, verbose_name='lymphocytes')),
                ('monocytes', models.FloatField(blank=True, null=True, verbose_name='monocytes')),
                ('plasmablasts', models.FloatField(blank=True, null=True, verbose_name='plasmablasts')),
                ('plasmacytes', models.FloatField(blank=True, null=True, verbose_name='plasmacytes')),
                ('platelets', models.FloatField(blank=True, null=True, verbose_name='platelets')),
                ('hospital_ft', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entrytool_bloodcountfollowup_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('hospital_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrytool.Hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entrytool_bloodcountfollowup_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('progression_date', models.DateField(verbose_name='Progresion/relapse date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entrytool_progression_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entrytool_progression_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='adverseevent',
            name='adverse_event_fk',
        ),
        migrations.RemoveField(
            model_name='adverseevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='adverseevent',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='adverseevent',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='mgus_history',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='mgus_history_date',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='smm_history',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='smm_history_date',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='date_of_last_visit',
            field=models.DateField(null=True, verbose_name='Date of last visit'),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='r_iss_stage',
            field=models.CharField(choices=[('Stage I', 'Stage I'), ('Stage II', 'Stage II'), ('Stage III', 'Stage III'), ('Unknown', 'Unknown')], default='', max_length=10, verbose_name='R-ISS Stage'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdverseEvent',
        ),
    ]
