# Generated by Django 2.0.13 on 2020-09-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0028_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='severity',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=4, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='death_cause',
            field=models.CharField(blank=True, choices=[('Disease', 'Disease'), ('Complications of Disease', 'Complications of Disease'), ('Other', 'Other')], max_length=100, null=True, verbose_name='Cause of Death'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='del_17p',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=10, verbose_name='del(17)p'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='mgus_history',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=10, verbose_name='History of MGUS'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='pp_type',
            field=models.CharField(choices=[('IgG', 'IgG'), ('IgA', 'IgA'), ('IgE', 'IgE'), ('Light Chain Myeloma', 'Light Chain Myeloma')], max_length=50, verbose_name='PP Type'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='r_iss_stage',
            field=models.CharField(choices=[('Stage I', 'Stage I'), ('Stage II', 'Stage II'), ('Stage III', 'Stage III')], max_length=10, verbose_name='R-ISS Stage'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='smm_history',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=10, verbose_name='History of SMM'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='status',
            field=models.CharField(choices=[('Under Treatment', 'Under Treatment'), ('Dead', 'Dead'), ('Lost to Follow-up', 'Lost to Follow-up')], max_length=100, verbose_name='Patient Status'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='t4_14',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=10, verbose_name='t(4;14)'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='t4_16',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=10, verbose_name='t(4;16)'),
        ),
        migrations.AlterField(
            model_name='sct',
            name='sct_type',
            field=models.CharField(choices=[('Allogenic', 'Allogenic'), ('Autologous', 'Autologous'), ('Unknown', 'Unknown')], max_length=12, null=True, verbose_name='Type of SCT'),
        ),
    ]
