# Generated by Django 2.0.13 on 2021-02-01 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0039_auto_20201007_1245'),
        ('entrytool', '0029_auto_20210126_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('ift_date', models.DateField(verbose_name='IFT Date')),
                ('MRD_status', models.CharField(blank=True, choices=[('Minimal', 'Minimal'), ('Non-minimal', 'Non-minimal')], max_length=25, null=True, verbose_name='MRD status')),
                ('percentage_tumor_cells', models.FloatField(blank=True, null=True, verbose_name='Percentage of tumor cells by IFT')),
                ('initial_tumor_phenotype', models.FloatField(blank=True, null=True, verbose_name='Initial phenotype of tumor cells')),
                ('phenotype', models.FloatField(blank=True, null=True, verbose_name='Phenotype')),
                ('cd38_138_presence', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=4, null=True, verbose_name='CD38/CD138 presence')),
                ('CD56_presence', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=4, null=True, verbose_name='CD56 presence')),
                ('CD19_presence', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=4, null=True, verbose_name='CD19 presence')),
                ('CD20_presence', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=4, null=True, verbose_name='CD20 presence')),
                ('CD27_presence', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=4, null=True, verbose_name='CD27 presence')),
                ('CD117_presence', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=4, null=True, verbose_name='CD117 presence')),
                ('CD38СD138_percentage', models.FloatField(blank=True, null=True, verbose_name='CD38/СD138, %')),
                ('CD56_percentage', models.FloatField(blank=True, null=True, verbose_name='CD56, %')),
                ('CD19_percentage', models.FloatField(blank=True, null=True, verbose_name='CD19, %')),
                ('CD20_percentage', models.FloatField(blank=True, null=True, verbose_name='CD20, %')),
                ('CD27_percentage', models.FloatField(blank=True, null=True, verbose_name='CD27, %')),
                ('CD117_percentage', models.FloatField(blank=True, null=True, verbose_name='CD117 , %')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entrytool_ift_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entrytool_ift_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='bloodcountfollowup',
            options={'verbose_name': 'Blood Count', 'verbose_name_plural': 'Blood Counts'},
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='risk_stratification',
            field=models.CharField(choices=[('Standard risk', 'Standard risk'), ('Intermediate risk', 'Intermediate risk'), ('High risk', 'High risk')], default='', max_length=25, verbose_name='Risk stratification'),
            preserve_default=False,
        ),
    ]
