# Generated by Django 2.0.13 on 2021-06-11 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0040_auto_20201007_1346'),
        ('entrytool', '0029_auto_20210611_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('characteristic_date', models.DateField(verbose_name='Date of measurement')),
                ('ecog_score', models.FloatField(blank=True, null=True, verbose_name='ECOG')),
                ('cirs_score', models.FloatField(blank=True, null=True, verbose_name='CIRS')),
                ('creatinine_clearance', models.FloatField(blank=True, null=True, verbose_name='Creatinine clearance')),
                ('B2M', models.FloatField(blank=True, null=True, verbose_name='Beta-2-Microglob')),
                ('LDH', models.FloatField(blank=True, null=True, verbose_name='LDH')),
                ('bulky_disease', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=25, null=True, verbose_name='Bulky disease present')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entrytool_additionalcharacteristics_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entrytool_additionalcharacteristics_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QualityOfLife5Q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('q5_date', models.DateField(verbose_name='Date of Questionnaire')),
                ('q5_mobility', models.FloatField(blank=True, null=True, verbose_name='Mobility')),
                ('q5_selfcare', models.FloatField(blank=True, null=True, verbose_name='Selfcare')),
                ('q5_usual_activities', models.FloatField(blank=True, null=True, verbose_name='Usual Activities')),
                ('q5_pain_discomfort', models.FloatField(blank=True, null=True, verbose_name='Pain/Discomfort')),
                ('q5_anxiety_depression', models.FloatField(blank=True, null=True, verbose_name='Anxiety/Depression')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entrytool_qualityoflife5q_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entrytool_qualityoflife5q_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
