# Generated by Django 2.0.13 on 2021-02-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0030_auto_20210201_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ift',
            old_name='CD38СD138_percentage',
            new_name='cd38cd138_percentage',
        ),
    ]
