# Generated by Django 2.0.13 on 2021-06-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0031_cytogenetics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(choices=[('CR', 'Complete Remission'), ('PD', 'Progressive Disease'), ('PR', 'Partial Response'), ('SD', 'Stable Disease')], max_length=50, verbose_name='Response'),
        ),
    ]
