# Generated by Django 2.0.13 on 2021-02-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0031_auto_20210201_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ift',
            old_name='CD117_percentage',
            new_name='cd117_percentage',
        ),
        migrations.RenameField(
            model_name='ift',
            old_name='CD117_presence',
            new_name='cd117_presence',
        ),
        migrations.RenameField(
            model_name='ift',
            old_name='CD19_percentage',
            new_name='cd19_percentage',
        ),
        migrations.RenameField(
            model_name='ift',
            old_name='CD19_presence',
            new_name='cd19_presence',
        ),
        migrations.RenameField(
            model_name='ift',
            old_name='CD20_percentage',
            new_name='cd20_percentage',
        ),
        migrations.RenameField(
            model_name='ift',
            old_name='CD20_presence',
            new_name='cd20_presence',
        ),
        migrations.RenameField(
            model_name='ift',
            old_name='CD27_percentage',
            new_name='cd27_percentage',
        ),
        migrations.RenameField(
            model_name='ift',
            old_name='CD27_presence',
            new_name='cd27_presence',
        ),
        migrations.RenameField(
            model_name='ift',
            old_name='CD56_percentage',
            new_name='cd56_percentage',
        ),
        migrations.RenameField(
            model_name='ift',
            old_name='CD56_presence',
            new_name='cd56_presence',
        ),
        migrations.AlterField(
            model_name='ift',
            name='initial_tumor_phenotype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Initial phenotype of tumor cells'),
        ),
        migrations.AlterField(
            model_name='ift',
            name='phenotype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phenotype'),
        ),
    ]
