# Generated by Django 2.0.13 on 2021-06-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0032_auto_20210611_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='del_13',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='del_17p',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='ds_stage',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='iss_stage',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='mgus_history',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='mgus_history_date',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='pp_type',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='smm_history',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='smm_history_date',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='t4_14',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='t4_16',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='binet_stage',
            field=models.CharField(choices=[('Stage A', 'Stage A'), ('Stage B', 'Stage B'), ('Stage C', 'Stage C')], default='', max_length=100, verbose_name='Binet Stage'),
            preserve_default=False,
        ),
    ]
