# Generated by Django 2.0.13 on 2021-02-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0032_auto_20210201_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='light_chain_type',
            field=models.CharField(choices=[('Kappa', 'Kappa'), ('Lambda', 'Lambda')], default='', max_length=25, verbose_name='Light Chain Type'),
            preserve_default=False,
        ),
    ]
