# Generated by Django 2.0.13 on 2021-02-03 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0039_auto_20201007_1245'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrytool', '0033_patientdetails_light_chain_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrabCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('crab_date', models.DateField(verbose_name='CRAB date')),
                ('hypercalcemia', models.NullBooleanField(verbose_name='Hypercalcemia')),
                ('calcium_level', models.CharField(choices=[('over2.65mmol', '> 2.65 mmol/L'), ('over1.5mmol', '> 1.5 mmol/L'), ('Unknown', 'Unknown')], max_length=30, verbose_name='Calcium Level')),
                ('renal_failure', models.NullBooleanField(verbose_name='creatinine >= 177 umol/L')),
                ('anemia', models.NullBooleanField(verbose_name='Hemoglobin < 100g/L or decrease of 20 g/d from norm')),
                ('bone_destruction', models.NullBooleanField(verbose_name='Bone destruction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entrytool_crabcriteria_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entrytool_crabcriteria_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
