# Generated by Django 2.0.13 on 2021-07-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0034_auto_20210621_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Best Response', 'verbose_name_plural': 'Responses'},
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='status',
            field=models.CharField(choices=[('Under Treatment', 'Under Treatment'), ('Dead', 'Dead'), ('Lost to Follow-up', 'Lost to Follow-up'), ('Watch and Wait', 'Watch and Wait'), ('Unknown', 'Unknown')], max_length=100, verbose_name='Patient Status'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(choices=[('CR', 'Complete Remission'), ('PD', 'Progressive Disease'), ('PR', 'Partial Response'), ('SD', 'Stable Disease'), ('Unknown', 'Unknown')], max_length=50, verbose_name='Best Response'),
        ),
    ]
