# Generated by Django 2.0.13 on 2021-08-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0035_auto_20210705_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimen',
            name='indefinite_duration',
            field=models.NullBooleanField(verbose_name='Treatment of indefinite duration'),
        ),
        migrations.AddField(
            model_name='regimen',
            name='part_of_clinical_trial',
            field=models.NullBooleanField(verbose_name='Regimen part of clinical trial'),
        ),
        migrations.AlterField(
            model_name='additionalcharacteristics',
            name='beta2m',
            field=models.FloatField(blank=True, null=True, verbose_name='Beta-2-Microglobulin'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='binet_stage',
            field=models.CharField(choices=[('Stage A', 'Stage A'), ('Stage B', 'Stage B'), ('Stage C', 'Stage C'), ('Unknown', 'Unknown')], max_length=100, verbose_name='Binet Stage'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='status',
            field=models.CharField(choices=[('Under Treatment', 'Under Treatment'), ('Dead', 'Dead'), ('Lost to Follow-up', 'Lost to Follow-up'), ('Watch and Wait', 'Watch and Wait'), ('In Remission', 'In Remission'), ('Observation after Treatment', 'Observation after Treatment'), ('Unknown', 'Unknown')], max_length=100, verbose_name='Patient Status'),
        ),
    ]
