# Generated by Django 2.0.13 on 2021-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0035_cytogenetics'),
    ]

    operations = [
        migrations.AddField(
            model_name='crabcriteria',
            name='nb_affected_zones',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of affected zones'),
        ),
        migrations.AddField(
            model_name='crabcriteria',
            name='region_osteolysis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Region of osteolysis'),
        ),
    ]
