# Generated by Django 2.0.13 on 2021-08-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0037_auto_20210820_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdetails',
            options={'verbose_name': 'Diagnosis details', 'verbose_name_plural': 'Diagnosis details'},
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='status',
        ),
    ]
