# Generated by Django 2.0.13 on 2021-02-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0037_auto_20210204_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crabcriteria',
            name='calcium_level',
        ),
        migrations.AddField(
            model_name='crabcriteria',
            name='ionized_over_15',
            field=models.NullBooleanField(verbose_name='Ionized calcium > 1.5 mmol/L'),
        ),
        migrations.AddField(
            model_name='crabcriteria',
            name='total_over_265',
            field=models.NullBooleanField(verbose_name='Total calcium > 2.65 mmol/'),
        ),
    ]
