# Generated by Django 2.0.13 on 2021-08-24 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0040_auto_20201007_1346'),
        ('entrytool', '0038_auto_20210824_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Date of Death')),
                ('death_cause', models.CharField(blank=True, choices=[('Disease', 'Disease'), ('Complications of Disease', 'Complications of Disease'), ('Other', 'Other')], max_length=100, null=True, verbose_name='Cause of Death')),
                ('lost_to_follow_up_date', models.DateField(blank=True, null=True, verbose_name='Lost to Follow-up')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entrytool_patientstatus_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entrytool_patientstatus_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Patient status',
                'verbose_name_plural': 'Patient status',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='death_cause',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='lost_to_follow_up_date',
        ),
    ]
