# Generated by Django 2.0.13 on 2021-02-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0038_auto_20210209_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='sct',
            name='cd_34_collection',
            field=models.NullBooleanField(verbose_name='CD34+ collection'),
        ),
        migrations.AddField(
            model_name='sct',
            name='mobilization_end',
            field=models.DateField(blank=True, null=True, verbose_name='End of mobilization'),
        ),
        migrations.AddField(
            model_name='sct',
            name='mobilization_regimen_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrytool.RegimenList'),
        ),
        migrations.AddField(
            model_name='sct',
            name='mobilization_regimen_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sct',
            name='mobilization_start',
            field=models.DateField(blank=True, null=True, verbose_name='Start of mobilization'),
        ),
        migrations.AddField(
            model_name='sct',
            name='mrd_sample',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MRD of bone marrow sample'),
        ),
    ]
