# Generated by Django 2.0.13 on 2021-08-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0039_auto_20210824_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstatus',
            name='deceased',
            field=models.NullBooleanField(verbose_name='Deceased'),
        ),
        migrations.AddField(
            model_name='patientstatus',
            name='lost_to_follow_up',
            field=models.NullBooleanField(verbose_name='Lost to Follow-Up'),
        ),
    ]
