# Generated by Django 2.0.13 on 2021-02-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0039_auto_20210209_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progression',
            options={'verbose_name': 'Progression/relapse', 'verbose_name_plural': 'Progression/relapse'},
        ),
    ]
