# Generated by Django 2.0.13 on 2021-08-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0040_auto_20210824_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regimen',
            name='category',
            field=models.CharField(choices=[('Treatment', 'Treatment'), ('Observation after remission', 'Observation after remission')], max_length=40, verbose_name='Regimen Type'),
        ),
    ]
