# Generated by Django 2.0.13 on 2021-09-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0041_auto_20210824_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcharacteristics',
            name='ecog_score',
            field=models.FloatField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='ECOG'),
        ),
        migrations.AlterField(
            model_name='cytogenetics',
            name='ighv_rearrangement',
            field=models.CharField(blank=True, choices=[('Mutated', 'Mutated'), ('Non-mutated', 'Non-mutated'), ('Unknown', 'Unknown')], max_length=25, null=True, verbose_name='IGHV rearrangement'),
        ),
    ]
