# Generated by Django 2.0.13 on 2021-02-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0041_radiationtherapy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcountfollowup',
            name='band_neutrophils',
            field=models.FloatField(blank=True, null=True, verbose_name='Band neutrophils'),
        ),
        migrations.AddField(
            model_name='bloodcountfollowup',
            name='esr',
            field=models.FloatField(blank=True, null=True, verbose_name='ESR'),
        ),
        migrations.AddField(
            model_name='bloodcountfollowup',
            name='segmented_neutrophils',
            field=models.FloatField(blank=True, null=True, verbose_name='Segmented neutrophils'),
        ),
        migrations.AddField(
            model_name='bloodcountfollowup',
            name='young_cells',
            field=models.FloatField(blank=True, null=True, verbose_name='Young cells'),
        ),
    ]
