# Generated by Django 2.0.13 on 2021-09-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0042_auto_20210914_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcharacteristics',
            name='ecog_score',
            field=models.FloatField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='ECOG'),
        ),
    ]
