# Generated by Django 2.0.13 on 2022-02-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0044_auto_20220217_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adverseevent',
            name='adverse_event_fk',
        ),
        migrations.RemoveField(
            model_name='adverseevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='adverseevent',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='adverseevent',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='AdverseEvent',
        ),
        migrations.DeleteModel(
            name='AEList',
        ),
    ]
