# Generated by Django 2.0.13 on 2022-08-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0045_auto_20220224_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='hospital_fk',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='FollowUp',
        ),
    ]
