# Generated by Django 2.2.16 on 2022-08-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0046_patientload'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientload',
            name='data_quality_completed',
            field=models.BooleanField(default=False, verbose_name='Data Quality Completed'),
        ),
    ]
