# Generated by Django 2.2.16 on 2022-08-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0046_patientload'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstatus',
            name='discharged',
            field=models.NullBooleanField(verbose_name='Discharged'),
        ),
    ]
