# Generated by Django 2.0.13 on 2022-04-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0046_demographics_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sct',
            name='alotph_conditioning',
            field=models.CharField(blank=True, choices=[('BU-FLU', 'BU-FLU'), ('TT-BU-FLU', 'TT-BU-FLU'), ('TT-FLU-BU', 'TT-FLU-BU'), ('Cyclophosphamide-ATG', 'Cyclophosphamide-ATG'), ('TT-BU-FLU-ATG', 'TT-BU-FLU-ATG'), ('TT-FLU-BU-ATG', 'TT-FLU-BU-ATG'), ('FLU-Cyclophosphamide-ATG', 'FLU-Cyclophosphamide-ATG'), ('FLU-ATG', 'FLU-ATG')], max_length=256, null=True, verbose_name='Conditioning'),
        ),
        migrations.AddField(
            model_name='sct',
            name='alotph_emr_technique',
            field=models.CharField(blank=True, choices=[('Tecnica NGS', 'Tecnica NGS'), ('Tecnica CFM (Flow Cytometry)', 'Tecnica CFM (Flow Cytometry)'), ('Both', 'Both')], max_length=256, null=True, verbose_name='EMR Technique'),
        ),
        migrations.AddField(
            model_name='sct',
            name='alotph_source',
            field=models.CharField(blank=True, choices=[('Bone Marrow', 'Bone Marrow'), ('Cord', 'Cord'), ('Peripheral Bloods', 'Peripheral Bloods'), ('Bone Marrow And Peripheral Bloods', 'Bone Marrow And Peripheral Bloods'), ('Other', 'Other'), ('Unknown', 'Unknown')], max_length=256, null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='sct',
            name='alotph_status',
            field=models.CharField(blank=True, choices=[('Complete Response Molecular', 'Complete Response Molecular'), ('Complete Response Immunophenotype', 'Complete Response Immunophenotype'), ('Complete Response Strict', 'Complete Response Strict'), ('Complete Response', 'Complete Response'), ('Very Good Partial Answer', 'Very Good Partial Answer'), ('Partial Response', 'Partial Response'), ('Stable Disease', 'Stable Disease'), ('Progression', 'Progression'), ('Unkown', 'Unkown'), ('Dead', 'Dead')], max_length=256, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='sct',
            name='atsp_conditioning',
            field=models.CharField(blank=True, choices=[('BEA', 'BEA'), ('BUCY', 'BUCY'), ('Melfalan 140', 'Melfalan 140'), ('Melfalan 200', 'Melfalan 200'), ('BU-MEL', 'BU-MEL'), ('BEAM', 'BEAM')], max_length=256, null=True, verbose_name='Conditioning'),
        ),
        migrations.AddField(
            model_name='sct',
            name='negativizacion_emr',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=256, null=True, verbose_name='Negativizacion EMR'),
        ),
        migrations.AddField(
            model_name='sct',
            name='negativizacion_emr_date',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=256, null=True, verbose_name='Negativizacion EMR Date'),
        ),
        migrations.AddField(
            model_name='sct',
            name='number_of_cells_infused',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Number Of Cells Infused'),
        ),
        migrations.AddField(
            model_name='sct',
            name='response',
            field=models.CharField(blank=True, choices=[('Complete Response Molecular', 'Complete Response Molecular'), ('Complete Response Immunophenotype', 'Complete Response Immunophenotype'), ('Complete Response Strict', 'Complete Response Strict'), ('Complete Response', 'Complete Response'), ('Very Good Partial Answer', 'Very Good Partial Answer'), ('Partial Response', 'Partial Response'), ('Stable Disease', 'Stable Disease'), ('Progression', 'Progression'), ('Unkown', 'Unkown'), ('Dead', 'Dead')], max_length=256, null=True, verbose_name='Response'),
        ),
        migrations.AddField(
            model_name='sct',
            name='response_date',
            field=models.DateField(blank=True, null=True, verbose_name='Response Date'),
        ),
        migrations.AddField(
            model_name='sct',
            name='type_of_alotph_transplant',
            field=models.CharField(blank=True, choices=[('HLA identical', 'HLA identical'), ('HLA identicofen', 'HLA identicofen'), ('Aplo: HLA unidentified related (>1 missmatch) phenotype', 'Aplo: HLA unidentified related (>1 missmatch) phenotype'), ('HLA no related ident (NO HAPLO: 1 missmatch)', 'HLA no related ident (NO HAPLO: 1 missmatch)'), ('HLA0 identical unrelated', 'HLA0 identical unrelated'), ('HLA-non-identical unrelated', 'HLA-non-identical unrelated'), ('An unknown', 'An unkown'), ('Other', 'Other')], max_length=256, null=True, verbose_name='Type Of Transplant'),
        ),
        migrations.AlterField(
            model_name='sct',
            name='sct_type',
            field=models.CharField(choices=[('Allogenic', 'Allogenic'), ('Autologous', 'Autologous'), ('Tandem ATSP', 'Tandem ATSP '), ('Unknown', 'Unknown')], max_length=12, null=True, verbose_name='Type of SCT'),
        ),
    ]
