# Generated by Django 2.0.13 on 2022-04-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0047_auto_20220427_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='sct',
            name='emr_technique',
            field=models.CharField(blank=True, choices=[('NGS', 'NGS'), ('FC (Flow Cytometry)', 'FC (Flow Cytometry)'), ('Both', 'Borth')], max_length=256, null=True, verbose_name='EMR2 Technique'),
        ),
    ]
