# Generated by Django 2.2.16 on 2022-08-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0047_patientstatus_discharged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientstatus',
            name='discharged',
        ),
    ]
