# Generated by Django 2.2.16 on 2022-08-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0047_patientload_data_quality_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientload',
            name='data_quality_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
