# Generated by Django 2.2.16 on 2022-08-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0048_patientload_data_quality_completed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientload',
            old_name='data_quality_completed_date',
            new_name='data_quality_reviewed_date',
        ),
        migrations.RemoveField(
            model_name='patientload',
            name='data_quality_completed',
        ),
        migrations.AddField(
            model_name='patientload',
            name='data_quality_reviewed',
            field=models.BooleanField(default=False, verbose_name='Data Quality Reviewed'),
        ),
    ]
