# Generated by Django 2.0.13 on 2022-04-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0048_sct_emr_technique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sct',
            name='alotph_emr_technique',
        ),
        migrations.RemoveField(
            model_name='sct',
            name='alotph_status',
        ),
        migrations.RemoveField(
            model_name='sct',
            name='emr_technique',
        ),
        migrations.RemoveField(
            model_name='sct',
            name='negativizacion_emr',
        ),
        migrations.RemoveField(
            model_name='sct',
            name='negativizacion_emr_date',
        ),
        migrations.RemoveField(
            model_name='sct',
            name='response',
        ),
        migrations.RemoveField(
            model_name='sct',
            name='response_date',
        ),
    ]
