# Generated by Django 2.2.16 on 2022-09-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0049_auto_20220818_1501'),
        ('entrytool', '0046_auto_20220803_0751'),
    ]

    operations = [
    ]
