# Generated by Django 2.2.16 on 2022-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0049_auto_20220818_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sct',
            name='sct_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of SCT'),
        ),
        migrations.AlterField(
            model_name='sct',
            name='sct_type',
            field=models.CharField(blank=True, choices=[('Allogenic', 'Allogenic'), ('Autologous', 'Autologous'), ('Unknown', 'Unknown')], max_length=12, null=True, verbose_name='Type of SCT'),
        ),
    ]
