# Generated by Django 2.2.16 on 2022-09-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0050_merge_20220915_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sct',
            name='sct_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of SCT'),
        ),
    ]
