# Generated by Django 2.2.16 on 2022-05-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0050_auto_20220502_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sct',
            old_name='type_of_alotph_transplant',
            new_name='relation',
        ),
        migrations.RemoveField(
            model_name='sct',
            name='hospital_fk',
        ),
        migrations.RemoveField(
            model_name='sct',
            name='hospital_ft',
        ),
        migrations.AddField(
            model_name='sct',
            name='tandem_astp',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=256, null=True, verbose_name='Tandem ASTP'),
        ),
        migrations.AlterField(
            model_name='sct',
            name='sct_type',
            field=models.CharField(choices=[('Allogenic', 'Allogenic'), ('Autologous', 'Autologous'), ('Unknown', 'Unknown')], max_length=12, null=True, verbose_name='Type of SCT'),
        ),
    ]
