# Generated by Django 2.2.16 on 2022-09-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0050_auto_20220915_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstatus',
            name='date_of_last_contact',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Last Contact'),
        ),
        migrations.AddField(
            model_name='patientstatus',
            name='physician',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Physician'),
        ),
        migrations.AddField(
            model_name='patientstatus',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Status'),
        ),
    ]
