# Generated by Django 2.2.16 on 2022-05-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0051_auto_20220504_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sct',
            name='relation',
            field=models.CharField(blank=True, choices=[('HLA identical', 'HLA identical'), ('HLA identicofen', 'HLA identicofen'), ('Aplo: HLA unidentified related (>1 missmatch) phenotype', 'Aplo: HLA unidentified related (>1 missmatch) phenotype'), ('HLA no related ident (NO HAPLO: 1 missmatch)', 'HLA no related ident (NO HAPLO: 1 missmatch)'), ('HLA0 identical unrelated', 'HLA0 identical unrelated'), ('HLA-non-identical unrelated', 'HLA-non-identical unrelated'), ('An unknown', 'An unkown'), ('Other', 'Other')], max_length=256, null=True, verbose_name='Relation'),
        ),
    ]
