# Generated by Django 2.2.16 on 2022-05-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0052_auto_20220505_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sct',
            name='sct_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of SCT'),
        ),
    ]
