# Generated by Django 2.2.16 on 2022-05-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0053_auto_20220505_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstatus',
            name='death_cause',
            field=models.CharField(blank=True, choices=[('Mieloma Multiple', 'Mieloma Multiple'), ('Infection', 'Infection'), ('Other', 'Other')], max_length=100, null=True, verbose_name='Cause of Death'),
        ),
    ]
