# Generated by Django 2.2.16 on 2022-06-30 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0054_auto_20220506_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sct',
            name='alotph_conditioning',
        ),
    ]
