# Generated by Django 2.2.16 on 2022-08-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0056_auto_20220630_1510'),
        ('entrytool', '0046_patientload'),
    ]

    operations = [
    ]
