# Generated by Django 2.2.16 on 2022-09-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0049_auto_20220818_1501'),
        ('entrytool', '0056_auto_20220630_1510'),
    ]

    operations = [
    ]
