# Generated by Django 2.0.13 on 2022-02-16 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrytool', '0043_auto_20210914_1147'),
    ]

    operations = [
    ]
