# Generated by Django 2.0.13 on 2022-02-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cll', '0005_copy_model_instances_into_cll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cllregimen',
            options={'verbose_name': 'Regimen', 'verbose_name_plural': 'Regimens'},
        ),
    ]
