# Generated by Django 2.0.13 on 2022-02-17 14:53
import datetime
from django.db import migrations


def forwards(apps, schema_editor):
    Episode = apps.get_model('opal', 'Episode')
    Episode.objects.filter(start=None).exclude(
        category_name="Treatment Line"
    ).update(
        start=datetime.date.today()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cll', '0005_copy_model_instances_into_cll'),
    ]

    operations = [
        migrations.RunPython(
            forwards
        )
    ]
