# Generated by Django 2.2.16 on 2022-08-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cll', '0007_auto_20220810_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestresponse',
            name='response_date',
            field=models.DateField(blank=True, null=True, verbose_name='Response Date'),
        ),
    ]
