# Generated by Django 2.2.16 on 2022-09-14 14:34

from django.db import migrations

TRANSLATION_MAPPING = {
    "CR": "Complete Remission",
    "PD": "Progressive Disease",
    "PR": "Partial Response",
    "SD": "Stable Disease",
}


def forwards(apps, schema_editor):
    BestResponse = apps.get_model(
        'cll', 'BestResponse'
    )
    for old, new in TRANSLATION_MAPPING.items():
        BestResponse.objects.filter(
            response=old
        ).update(
            response=new
        )


def backwards(apps, schema_editor):
    BestResponse = apps.get_model(
        'cll', 'BestResponse'
    )
    for old, new in TRANSLATION_MAPPING.items():
        BestResponse.objects.filter(
            response=new
        ).update(
            response=old
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cll', '0007_auto_20220914_1433'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=backwards),
    ]
