# Generated by Django 2.2.16 on 2022-09-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cll', '0007_auto_20220914_1433'),
        ('cll', '0009_auto_20220822_0747'),
    ]

    operations = [
    ]
