# Generated by Django 2.2.16 on 2022-09-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cll', '0010_merge_20220915_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestresponse',
            options={'verbose_name': 'Best response', 'verbose_name_plural': 'Best responses'},
        ),
    ]
