# Generated by Django 2.0.13 on 2022-04-22 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0042_auto_20220421_1545'),
        ('mm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMPastMedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('previous_neoplasm', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=256, null=True, verbose_name='Previous Neoplasm')),
                ('previous_neoplasm_date_of_diagnosis', models.DateField(blank=True, null=True, verbose_name='Date Of Diagnosis')),
                ('previous_neoplasm_details', models.TextField(blank=True, default='', verbose_name='Details')),
                ('previous_neoplasm_2', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=256, null=True, verbose_name='Second Prevous Neoplasm')),
                ('previous_neoplasm_date_of_diagnosis_2', models.DateField(blank=True, null=True, verbose_name='Date Of Diagnosis')),
                ('previous_neoplasm_details_2', models.TextField(blank=True, default='', verbose_name='Details')),
                ('chronic_renal_insufficiency', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=256, null=True, verbose_name='Chronic Renal Insufficiency')),
                ('chronic_renal_insufficiency_diagnosis_date', models.DateField(blank=True, null=True, verbose_name='Diagnosis Date')),
                ('monoclonal_pathology', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=256, null=True, verbose_name='Monoclonal Pathology')),
                ('symtomatic_multiple_myeloma', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=256, null=True, verbose_name='Symtomatic Multiple Myeloma')),
                ('asymtomatic_multiple_myeloma', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=256, null=True, verbose_name='Asymtomatic Multiple Myeloma')),
                ('monoclonal_pathology_of_uncertain_meaning', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=256, null=True, verbose_name='Monoclonal Pathology Of Uncertain Meaning')),
                ('monoclonal_pathology_of_uncertain_meaning_date', models.DateField(blank=True, null=True, verbose_name='Diagnosis Date')),
                ('external_pasmocytoma', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=256, null=True, verbose_name='External Pasmocytoma')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Comments')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mm_mmpastmedicalhistory_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mm_mmpastmedicalhistory_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Past Medical History',
                'verbose_name_plural': 'Past Medical Histories',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
