# Generated by Django 2.0.13 on 2022-08-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmdiagnosisdetails',
            name='heavy_chain_type',
            field=models.CharField(blank=True, choices=[('IgG', 'IgG'), ('IgD', 'IgD'), ('IgA', 'IgA'), ('IgM', 'IgM'), ('IgE', 'IgE'), ('No Heavy Chain', 'No Heavy Chain'), ('Other', 'Other')], max_length=256, null=True, verbose_name='Heavy chain type'),
        ),
        migrations.AddField(
            model_name='mmdiagnosisdetails',
            name='light_chain_type',
            field=models.CharField(blank=True, choices=[('Kappa', 'Kappa'), ('Lambda', 'Lambda'), ('Non-Secretory', 'Non-Secretory'), ('No Light Chain', 'No Light Chain')], max_length=256, null=True, verbose_name='Light chain type'),
        ),
    ]
