# Generated by Django 2.2.16 on 2022-09-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0002_mmstemcelltransplanteligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmstemcelltransplanteligibility',
            name='eligable_for_stem_cell_transplant',
            field=models.BooleanField(default=False, verbose_name='Eligable For Stem Cell Transplant'),
        ),
    ]
