# Generated by Django 2.0.13 on 2022-08-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0002_auto_20220802_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmresponse',
            name='progression_date',
            field=models.DateField(blank=True, null=True, verbose_name='Progression Date'),
        ),
    ]
