# Generated by Django 2.0.13 on 2022-04-21 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mm', '0002_mmcytogenetics'),
    ]

    operations = [
        migrations.CreateModel(
            name='labTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('lab_test_date', models.DateField(verbose_name='Test date')),
                ('hemoglobin', models.FloatField(blank=True, null=True, verbose_name='hemoglobin')),
                ('leukocytes', models.FloatField(blank=True, null=True, verbose_name='leukocytes')),
                ('creatinine', models.FloatField(blank=True, null=True, verbose_name='creatinine')),
                ('ldh', models.FloatField(blank=True, null=True, verbose_name='LDH')),
                ('albumin', models.FloatField(blank=True, null=True, verbose_name='albumin')),
                ('calcium', models.FloatField(blank=True, null=True, verbose_name='calcium')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mm_labtests_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mm_labtests_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Lab tests',
                'verbose_name_plural': 'Lab tests',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
