# Generated by Django 2.0.13 on 2022-08-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0003_mmresponse_progression_date'),
        ('mm', '0002_mmstemcelltransplanteligibility'),
    ]

    operations = [
    ]
