# Generated by Django 2.2.16 on 2022-09-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0003_auto_20220811_1047'),
        ('mm', '0003_auto_20220915_0940'),
    ]

    operations = [
    ]
