# Generated by Django 2.2.16 on 2022-09-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0003_auto_20220915_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmstemcelltransplanteligibility',
            name='eligable_for_stem_cell_transplant',
        ),
        migrations.AddField(
            model_name='mmstemcelltransplanteligibility',
            name='eligible_for_stem_cell_transplant',
            field=models.BooleanField(default=False, verbose_name='Eligible For Stem Cell Transplant'),
        ),
    ]
