# Generated by Django 2.2.16 on 2022-08-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0004_auto_20220815_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmdiagnosisdetails',
            old_name='diagnosis_date',
            new_name='diag_date',
        ),
    ]
