# Generated by Django 2.0.13 on 2022-04-27 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mm', '0004_auto_20220427_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiotherapyInduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mm_radiotherapyinduction_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mm_radiotherapyinduction_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Radiotherapy Induction',
                'verbose_name_plural': 'Radiotherapy Inductions',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='radiotherapy',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='radiotherapy',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='radiotherapy',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='mmregimen',
            name='emr_technique',
        ),
        migrations.RemoveField(
            model_name='mmregimen',
            name='regimen_description',
        ),
        migrations.RemoveField(
            model_name='mmregimen',
            name='response_date',
        ),
        migrations.RemoveField(
            model_name='mmregimen',
            name='stop_reason_description',
        ),
        migrations.AddField(
            model_name='mmregimen',
            name='regimen_details',
            field=models.TextField(blank=True, default='', verbose_name='Regimen Details'),
        ),
        migrations.AddField(
            model_name='mmregimen',
            name='stop_reason_details',
            field=models.TextField(blank=True, default='', verbose_name='Stop Reason Details'),
        ),
        migrations.DeleteModel(
            name='Radiotherapy',
        ),
    ]
