# Generated by Django 2.2.16 on 2022-09-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0004_merge_20220915_1005'),
    ]

    operations = [
    ]
