# Generated by Django 2.0.13 on 2022-04-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0005_auto_20220427_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmdiagnosisdetails',
            name='infection_type',
            field=models.CharField(blank=True, choices=[('Clinically Documented Infection', 'Clinically Documented Infection'), ('Undocumented Infection', 'Undocumented Infection'), ('Microbiologically Documented Without Bacteremia', 'Microbiologically Documented Without Bacteremia'), ('Microbiologically Documented With Bacteremia', 'Microbiologically Documented With Bacteremia'), ('Other Microbiologic Documented Infection', 'Other Microbiologic Documented Infection')], max_length=256, null=True, verbose_name='Infection_Type'),
        ),
    ]
