# Generated by Django 2.0.13 on 2022-08-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrytool', '0046_auto_20220803_0751'),
        ('mm', '0005_auto_20220803_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmcytogenetics',
            name='hospital_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrytool.Hospital'),
        ),
        migrations.AddField(
            model_name='mmcytogenetics',
            name='hospital_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
