# Generated by Django 2.0.13 on 2022-08-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0006_auto_20220803_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='calcium',
            field=models.FloatField(blank=True, max_length=256, null=True, verbose_name='Calcium'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='creatinine',
            field=models.FloatField(blank=True, max_length=256, null=True, verbose_name='Creatinine'),
        ),
        migrations.AddField(
            model_name='mmcytogenetics',
            name='ighv_rearrangement',
            field=models.CharField(blank=True, choices=[('Mutated', 'Mutated'), ('Non-mutated', 'Non-mutated'), ('Unknown', 'Unknown')], max_length=25, null=True, verbose_name='IGHV rearrangement'),
        ),
    ]
