# Generated by Django 2.0.13 on 2022-04-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0007_auto_20220427_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientoutcome',
            options={'verbose_name': 'Patient Status', 'verbose_name_plural': 'Patient Statuses'},
        ),
        migrations.AlterField(
            model_name='mmpastmedicalhistory',
            name='chronic_renal_insufficiency_diagnosis_date',
            field=models.DateField(blank=True, null=True, verbose_name='Insufficiency Date'),
        ),
    ]
