# Generated by Django 2.0.13 on 2022-08-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0008_auto_20220803_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmcytogenetics',
            name='ighv_rearrangement',
        ),
        migrations.AddField(
            model_name='labtest',
            name='iga_count',
            field=models.FloatField(blank=True, null=True, verbose_name='IgA Count'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='igd_count',
            field=models.FloatField(blank=True, null=True, verbose_name='IgD Count'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='ige_count',
            field=models.FloatField(blank=True, null=True, verbose_name='IgE Count'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='igg_count',
            field=models.FloatField(blank=True, null=True, verbose_name='IgG Count'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='igm_count',
            field=models.FloatField(blank=True, null=True, verbose_name='IgM Count'),
        ),
        migrations.AddField(
            model_name='mmcytogenetics',
            name='ighv',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=25, null=True, verbose_name='IGHV'),
        ),
        migrations.AddField(
            model_name='mmcytogenetics',
            name='tp_53',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=10, null=True, verbose_name='tp 53)'),
        ),
        migrations.AlterField(
            model_name='mmcytogenetics',
            name='del1p',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=10, verbose_name='del 1p'),
        ),
        migrations.AlterField(
            model_name='mmcytogenetics',
            name='del_17p',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=10, verbose_name='del(17)p'),
        ),
        migrations.AlterField(
            model_name='mmcytogenetics',
            name='t11_14',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=10, null=True, verbose_name='t(11;14)'),
        ),
        migrations.AlterField(
            model_name='mmcytogenetics',
            name='t4_14',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=10, null=True, verbose_name='t(4;14)'),
        ),
        migrations.AlterField(
            model_name='mmcytogenetics',
            name='t4_14_16',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=10, null=True, verbose_name='t(14;16)'),
        ),
        migrations.AlterField(
            model_name='mmcytogenetics',
            name='t4_14_haploid_karyotype',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=256, null=True, verbose_name='t(4;14) Haploid Karyotype'),
        ),
        migrations.AlterField(
            model_name='mmcytogenetics',
            name='t4_14_not_effected',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=256, null=True, verbose_name='t(4;14) Not Effected'),
        ),
    ]
