# Generated by Django 2.0.13 on 2022-08-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0009_auto_20220803_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmcytogenetics',
            name='del_17p',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=10, verbose_name='del 17p'),
        ),
        migrations.AlterField(
            model_name='mmcytogenetics',
            name='t4_14',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=10, null=True, verbose_name='t4;14)'),
        ),
        migrations.AlterField(
            model_name='mmcytogenetics',
            name='t4_14_16',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=10, null=True, verbose_name='t14;16'),
        ),
    ]
