# Generated by Django 2.0.13 on 2022-04-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0010_auto_20220428_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmregimen',
            name='negative_mrd',
        ),
        migrations.RemoveField(
            model_name='mmregimen',
            name='negative_mrd_date',
        ),
        migrations.AddField(
            model_name='mmresponse',
            name='mrd_technique',
            field=models.CharField(blank=True, choices=[('NGS', 'NGS'), ('FC (Flow Cytometry)', 'FC (Flow Cytometry)'), ('Both', 'Both')], max_length=256, null=True, verbose_name='MRD Technique'),
        ),
        migrations.AddField(
            model_name='mmresponse',
            name='negative_mrd',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=256, null=True, verbose_name='Negative MRD'),
        ),
        migrations.AddField(
            model_name='mmresponse',
            name='negative_mrd_date',
            field=models.DateField(blank=True, null=True, verbose_name='Negative MRD Date'),
        ),
    ]
