# Generated by Django 2.0.13 on 2022-08-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0010_auto_20220803_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmcytogenetics',
            name='t4_14',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=10, null=True, verbose_name='t4;14'),
        ),
        migrations.AlterField(
            model_name='mmcytogenetics',
            name='tp_53',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=10, null=True, verbose_name='tp 53'),
        ),
    ]
