# Generated by Django 2.0.13 on 2022-04-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0011_auto_20220428_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='imaging',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='labtests',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='mproteinmesurements',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
