# Generated by Django 2.0.13 on 2022-08-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0011_auto_20220803_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmregimen',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
