# Generated by Django 2.2.16 on 2022-09-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0006_merge_20220915_1620'),
        ('mm', '0011_auto_20220803_1244'),
    ]

    operations = [
    ]
