# Generated by Django 2.0.13 on 2022-05-01 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0042_auto_20220421_1545'),
        ('mm', '0012_auto_20220428_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('condition', models.CharField(blank=True, choices=[('Renal Failure', 'Renal Failure'), ('Neuropathy', 'Neuropathy'), ('Hemorrhage', 'Hemorrhage'), ('Fever', 'Fever'), ('Infection', 'Infection'), ('Other', 'Other')], max_length=256, null=True, verbose_name='Condition')),
                ('infection_type', models.CharField(blank=True, choices=[('Undocumented Preinfection', 'Undocumented Preinfection'), ('Microbiologically Documented Without Bacteremia', 'Microbiologically Documented Without Bacteremia'), ('Microbiologically Documented With Bacteremia', 'Microbiologically Documented With Bacteremia'), ('Clinically Documented', 'Clinically Documente')], max_length=256, null=True, verbose_name='Infection Type')),
                ('type_of_microorganism_infection', models.CharField(blank=True, max_length=256, null=True, verbose_name='Type Of Microorganism Infection')),
                ('infection_source', models.CharField(blank=True, max_length=256, null=True, verbose_name='Infection Source')),
                ('other_condition_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Condition Name')),
                ('details', models.TextField(blank=True, default='', verbose_name='Details')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mm_comorbidity_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mm_comorbidity_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Comorbidity',
                'verbose_name_plural': 'Comorbidities',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('date', models.TextField(blank=True, default='', verbose_name='Date')),
                ('response_at_last_visit', models.TextField(blank=True, default='', verbose_name='Response At Last Visit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mm_review_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mm_review_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='conditionatinduction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='conditionatinduction',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='conditionatinduction',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='mmregimen',
            name='start_reason',
            field=models.TextField(blank=True, default='', verbose_name='Start Reason Details'),
        ),
        migrations.AddField(
            model_name='mmresponse',
            name='progression_date',
            field=models.DateField(blank=True, null=True, verbose_name='Progression Date'),
        ),
        migrations.AlterField(
            model_name='mmregimen',
            name='category',
            field=models.CharField(choices=[('Induction', 'Induction'), ('Maintenance', 'Maintenance'), ('Conditioning', 'Conditioning'), ('Relapse', 'Relapse'), ('Watch and wait', 'Watch and wait'), ('Other', 'Other')], max_length=40, verbose_name='Regimen Type'),
        ),
        migrations.DeleteModel(
            name='ConditionAtInduction',
        ),
    ]
