# Generated by Django 2.0.13 on 2022-08-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0012_auto_20220809_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmresponse',
            name='response_date',
            field=models.DateField(blank=True, null=True, verbose_name='Response Date'),
        ),
    ]
