# Generated by Django 2.2.16 on 2022-09-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0014_auto_20220921_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmregimen',
            name='end_treatment_reason',
            field=models.TextField(blank=True, default='', verbose_name='End Treatment Reason'),
        ),
    ]
