# Generated by Django 2.2.16 on 2022-05-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0014_auto_20220501_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, verbose_name='Date'),
        ),
    ]
