# Generated by Django 2.2.16 on 2022-05-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0015_auto_20220502_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmpatientstatus',
            name='status_date',
        ),
    ]
