# Generated by Django 2.2.16 on 2022-09-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0015_mmregimen_end_treatment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
