# Generated by Django 2.2.16 on 2022-09-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0016_auto_20220922_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmdiagnosisdetails',
            name='r_iss_stage',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=10, null=True, verbose_name='R ISS Stage'),
        ),
    ]
