# Generated by Django 2.2.16 on 2022-05-02 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0042_auto_20220421_1545'),
        ('mm', '0016_remove_mmpatientstatus_status_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('pcr', models.IntegerField(blank=True, null=True, verbose_name='PCR')),
                ('celulas_plasmaticas_circulantes', models.FloatField(blank=True, max_length=256, null=True, verbose_name='Celulas Plasmaticas Circulantes')),
                ('troponina', models.IntegerField(blank=True, null=True, verbose_name='Troponina')),
                ('total_proteins', models.IntegerField(blank=True, null=True, verbose_name='Total Proteins')),
                ('platelets', models.IntegerField(blank=True, null=True, verbose_name='Platelets')),
                ('beta_2_microglobulin', models.FloatField(blank=True, max_length=256, null=True, verbose_name='Beta 2 Microglobulin')),
                ('alkaline_phosphatase', models.IntegerField(blank=True, null=True, verbose_name='Alkaline Phosphatase')),
                ('albumin', models.FloatField(blank=True, max_length=256, null=True, verbose_name='Albumin')),
                ('creatinine', models.FloatField(blank=True, max_length=256, null=True, verbose_name='Creatinine')),
                ('calcium', models.FloatField(blank=True, max_length=256, null=True, verbose_name='Calcium')),
                ('hemoglobin', models.FloatField(blank=True, max_length=256, null=True, verbose_name='Hemoglobin')),
                ('proteinuria', models.FloatField(blank=True, max_length=256, null=True, verbose_name='Proteinuria')),
                ('proteinuria_g24', models.FloatField(blank=True, max_length=256, null=True, verbose_name='Proteinuria gr/24')),
                ('leucocytes', models.FloatField(blank=True, max_length=256, null=True, verbose_name='Leucocytes')),
                ('nt_pro_bnp', models.IntegerField(blank=True, null=True, verbose_name='NT-proBNP')),
                ('ldh', models.IntegerField(blank=True, null=True, verbose_name='LDH')),
                ('ldh_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='LDH Type')),
                ('glomerular_filtration_formula_date', models.DateField(blank=True, null=True, verbose_name='Glomerular Filtration Formula Date')),
                ('glomerular_filtration_formula', models.CharField(blank=True, choices=[('MDRD', 'MDRD'), ('CKD-EPI', 'CKD-EPI'), ('Other', 'Other')], max_length=256, null=True, verbose_name='Glomerular Filtration Formula')),
                ('glomerular_filtration', models.FloatField(blank=True, max_length=256, null=True, verbose_name='Glomerular Filtration')),
                ('filter_formula_description', models.TextField(blank=True, default='', verbose_name='Filter Formula Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mm_labtest_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mm_labtest_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='review',
            name='response_at_last_visit',
            field=models.TextField(blank=True, null=True, verbose_name='Response At Last Visit'),
        ),
        migrations.DeleteModel(
            name='LabTests',
        ),
    ]
