# Generated by Django 2.2.16 on 2022-05-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0017_auto_20220503_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='troponina',
            field=models.FloatField(blank=True, null=True, verbose_name='Troponina'),
        ),
    ]
