# Generated by Django 2.2.16 on 2022-05-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0018_auto_20220503_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='alkaline_phosphatase',
            field=models.FloatField(blank=True, null=True, verbose_name='Alkaline Phosphatase'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='total_proteins',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Proteins'),
        ),
    ]
