# Generated by Django 2.2.16 on 2022-05-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0019_auto_20220503_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
