# Generated by Django 2.2.16 on 2022-05-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0021_auto_20220503_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='celulas_plasmaticas_circulantes',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='troponina',
        ),
        migrations.AddField(
            model_name='labtest',
            name='circulating_plasma_cells',
            field=models.FloatField(blank=True, max_length=256, null=True, verbose_name='Circulating Plasma Cells'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='troponine',
            field=models.FloatField(blank=True, null=True, verbose_name='Troponine'),
        ),
    ]
