# Generated by Django 2.2.16 on 2022-05-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0023_auto_20220503_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='pcr',
            field=models.FloatField(blank=True, null=True, verbose_name='PCR'),
        ),
    ]
