# Generated by Django 2.2.16 on 2022-05-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0024_auto_20220503_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmpatientstatus',
            old_name='status_date',
            new_name='date_of_death',
        ),
    ]
