# Generated by Django 2.2.16 on 2022-05-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0026_auto_20220504_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmpastmedicalhistory',
            name='previous_neoplasm_date_of_diagnosis_2',
        ),
        migrations.RemoveField(
            model_name='mmpastmedicalhistory',
            name='previous_neoplasm_details_2',
        ),
    ]
