# Generated by Django 2.2.16 on 2022-05-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0027_auto_20220504_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonedisease',
            name='treatment_details',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Treatment Details'),
        ),
    ]
