# Generated by Django 2.2.16 on 2022-05-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0028_bonedisease_treatment_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmdiagnosisdetails',
            old_name='date_of_diagnosis',
            new_name='diagnosis_date',
        ),
        migrations.AlterField(
            model_name='mmregimen',
            name='category',
            field=models.CharField(choices=[('Induction', 'Induction'), ('Maintenance', 'Maintenance'), ('Consolidation', 'Consolidation'), ('Relapse', 'Relapse'), ('Watch and wait', 'Watch and wait'), ('Other', 'Other')], max_length=40, verbose_name='Regimen Type'),
        ),
    ]
