# Generated by Django 2.2.16 on 2022-05-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0030_auto_20220505_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmdiagnosisdetails',
            name='subclassification',
        ),
        migrations.AddField(
            model_name='mmdiagnosisdetails',
            name='heavy_chain_type',
            field=models.CharField(blank=True, choices=[('IgG', 'IgG'), ('IgD', 'IgD'), ('IgA', 'IgA'), ('IgM', 'IgM'), ('IgE', 'IgE'), ('No Heavy Chain', 'No Heavy Chain'), ('Other', 'Other')], max_length=256, null=True, verbose_name='Heavy chain type'),
        ),
        migrations.AddField(
            model_name='mmdiagnosisdetails',
            name='light_chain_type',
            field=models.CharField(blank=True, choices=[('Kappa', 'Kappa'), ('Lambda', 'Lambda')], max_length=256, null=True, verbose_name='Light chain type'),
        ),
    ]
