# Generated by Django 2.2.16 on 2022-05-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0031_auto_20220506_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmdiagnosisdetails',
            name='light_chain_type',
            field=models.CharField(blank=True, choices=[('Kappa', 'Kappa'), ('Lambda', 'Lambda'), ('Non-Secretory', 'Non-Secretory'), ('No Light Chain', 'No Light Chain')], max_length=256, null=True, verbose_name='Light chain type'),
        ),
        migrations.AlterField(
            model_name='mproteinmesurements',
            name='light_chain_type',
            field=models.CharField(blank=True, choices=[('Kappa', 'Kappa'), ('Lambda', 'Lambda'), ('Non-Secretory', 'Non-Secretory'), ('No Light Chain', 'No Light Chain')], max_length=256, null=True, verbose_name='Light Chain Type'),
        ),
    ]
