# Generated by Django 2.2.16 on 2022-05-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0032_auto_20220506_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mproteinmesurements',
            name='serum_amount',
            field=models.FloatField(blank=True, max_length=256, null=True, verbose_name='Monoclonal serum amount'),
        ),
    ]
