# Generated by Django 2.2.16 on 2022-05-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0033_auto_20220506_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comorbidity',
            name='infection_type',
            field=models.CharField(blank=True, choices=[('Undocumented Preinfection', 'Undocumented Preinfection'), ('Microbiologically Documented Without Bacteremia', 'Microbiologically Documented Without Bacteremia'), ('Microbiologically Documented With Bacteremia', 'Microbiologically Documented With Bacteremia'), ('Clinically Documented', 'Clinically Documented')], max_length=256, null=True, verbose_name='Infection Type'),
        ),
    ]
