# Generated by Django 2.2.16 on 2022-05-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0034_auto_20220506_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmdiagnosisdetails',
            name='ircp_diag_date',
        ),
    ]
