# Generated by Django 2.2.16 on 2022-09-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0006_merge_20220915_1620'),
        ('mm', '0035_remove_mmdiagnosisdetails_ircp_diag_date'),
    ]

    operations = [
    ]
