# Generated by Django 2.2.16 on 2022-09-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0036_merge_20220916_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmfollowup',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Visit date'),
        ),
        migrations.AlterField(
            model_name='mmresponse',
            name='response',
            field=models.CharField(blank=True, choices=[('Minimal response', 'Minimal response'), ('Partial response', 'Partial response'), ('Very good partial response', 'Very good partial response'), ('Complete response', 'Complete response'), ('Stringent complete response', 'Stringent complete response'), ('Near complete response', 'Near complete response'), ('Immunophenotypic complete response', 'Immunophenotypic complete response'), ('Stable disease', 'Stable disease'), ('Progressive disease', 'Progressive disease'), ('Response unknown/NA', 'Response unknown/NA')], max_length=50, null=True, verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='mmstemcelltransplanteligibility',
            name='eligible_for_stem_cell_transplant',
            field=models.BooleanField(default=False, verbose_name='Eligible For Stem Cell Transplant'),
        ),
    ]
