# Generated by Django 2.2.16 on 2022-09-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0037_auto_20220916_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmdiagnosisdetails',
            old_name='diagnosis_date',
            new_name='diag_date',
        ),
    ]
