# Generated by Django 2.2.16 on 2022-09-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0038_auto_20220916_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='lymphocytes',
            field=models.FloatField(blank=True, max_length=256, null=True, verbose_name='Lymphocytes'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='neutrophils',
            field=models.FloatField(blank=True, max_length=256, null=True, verbose_name='Neutrophils'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='platelets',
            field=models.FloatField(blank=True, max_length=256, null=True, verbose_name='Platelets'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='total_proteins',
            field=models.FloatField(blank=True, max_length=256, null=True, verbose_name='Total proteins'),
        ),
    ]
