# Generated by Django 2.2.16 on 2022-09-26 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0042_auto_20220421_1545'),
        ('mm', '0039_auto_20220923_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='circulating_plasma_cells',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='filter_formula_description',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='glomerular_filtration_formula',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='glomerular_filtration_formula_date',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='ldh_type',
        ),
        migrations.RemoveField(
            model_name='mproteinmesurements',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mproteinmesurements',
            name='freelite_count',
        ),
        migrations.RemoveField(
            model_name='mproteinmesurements',
            name='heavy_chain_type',
        ),
        migrations.RemoveField(
            model_name='mproteinmesurements',
            name='heavy_chain_type_other',
        ),
        migrations.RemoveField(
            model_name='mproteinmesurements',
            name='heavylite_count',
        ),
        migrations.RemoveField(
            model_name='mproteinmesurements',
            name='light_chain_type',
        ),
        migrations.CreateModel(
            name='Immunofixation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('monoclonal_ig_g_protein_serum', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unrealized', 'Unrealized')], max_length=256, null=True, verbose_name='Monoclonal IgG Protein (Serum)')),
                ('monoclonal_ig_a_protein_serum', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unrealized', 'Unrealized')], max_length=256, null=True, verbose_name='Monoclonal IgA Protein (Serum)')),
                ('monoclonal_ig_m_protein_serum', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unrealized', 'Unrealized')], max_length=256, null=True, verbose_name='Monoclonal IgM Protein (Serum)')),
                ('monoclonal_kappa_chain_serum', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unrealized', 'Unrealized')], max_length=256, null=True, verbose_name='Monoclonal Kappa chain (Serum)')),
                ('monoclonal_lambda_chain_serum', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unrealized', 'Unrealized')], max_length=256, null=True, verbose_name='Monoclonal Lambda chain (Serum)')),
                ('immunifixaction_profile_serum', models.TextField(blank=True, null=True, verbose_name='Immunifixaction Profile (Serum)')),
                ('immunifixaction_profile_urine', models.TextField(blank=True, null=True, verbose_name='Immunifixaction Profile (Urine)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mm_immunofixation_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode', verbose_name='Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mm_immunofixation_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
