# Generated by Django 2.2.16 on 2022-09-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0040_auto_20220926_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmpatientstatus',
            name='last_seen',
            field=models.DateField(blank=True, null=True, verbose_name='Last Seen'),
        ),
        migrations.AlterField(
            model_name='mproteinmesurements',
            name='plasma_cells_in_bone_marrow',
            field=models.FloatField(blank=True, max_length=256, null=True, verbose_name='Plasma Cells In Bone Marrow'),
        ),
    ]
