# Generated by Django 2.2.16 on 2023-04-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0041_auto_20220926_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunofixation',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='mproteinmesurements',
            name='plasma_cells_in_bone_marrow',
            field=models.FloatField(blank=True, max_length=256, null=True, verbose_name='Plasma Cells In Bone Marrow'),
        ),
    ]
