# Generated by Django 2.2.16 on 2023-04-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0043_labtest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mproteinmesurements',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
