version: "3.8"
   
services:
  web:
    build: ./entrytool
    working_dir: /code
    command: bash -c "gunicorn -b 0.0.0.0:8000 entrytool.wsgi"
    expose:
      - 8000

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    